version: '3.8'
services:
  db:
    image: postgres:14.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: qZ5jujUUAEiOvmbki25XnA==
      POSTGRES_DB: nest
    networks:
      - app_network
    restart: unless-stopped
  test-db:
    image: postgres:14.5
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://api:qZ5jujUUAEiOvmbki25XnA==@db:5432/nest'
      PASSWORD_HASHING_ALG: 'ARGON2'
      ARGON2_ITERATIONS: 1
      ARGON2_MEMORY_KB: 854071
      ARGON2_PARALLELISM: 16
      ARGON2_HASHING_POOL_SIZE: 1
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge
