version: '3.8'
services:
  db:
    image: postgres:14.5
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app_network
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - db
    ports:
      - ${SUPERTOKENS_PORT}:3567
    environment:
      POSTGRESQL_CONNECTION_URI: ${SUPERTOKENS_CONNECTION_URI}
      PASSWORD_HASHING_ALG: ${SUPERTOKENS_HASHING_ALGORITHM}
      ARGON2_ITERATIONS: ${ARGON2_ITERATIONS}
      ARGON2_MEMORY_KB: ${ARGON2_MEMORY_KB}
      ARGON2_PARALLELISM: ${ARGON2_PARALLELISM}
      ARGON2_HASHING_POOL_SIZE: ${ARGON2_HASHING_POOL_SIZE}
    networks:
      - app_network

  test-db:
    image: postgres:14.5
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app_network
  test-supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - test-db
    ports:
      - ${SUPERTOKENS_PORT}:3567
    environment:
      POSTGRESQL_CONNECTION_URI: ${SUPERTOKENS_CONNECTION_URI}
      PASSWORD_HASHING_ALG: ${SUPERTOKENS_HASHING_ALGORITHM}
      ARGON2_ITERATIONS: ${ARGON2_ITERATIONS}
      ARGON2_MEMORY_KB: ${ARGON2_MEMORY_KB}
      ARGON2_PARALLELISM: ${ARGON2_PARALLELISM}
      ARGON2_HASHING_POOL_SIZE: ${ARGON2_HASHING_POOL_SIZE}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
